title: "Semester 5"

# theme: jekyll-theme-hacker
remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-picture-tag
  - jekyll-pwa-workbox
  - jemoji
  - searchyll

relative_links:
  enabled: true
  collections: true

include:
  - README.md

# searchyll
# https://github.com/omc/searchyll#configuration
elasticsearch:
  url: "https://solutions.sem5.tk"     # Required. Supports auth and SSL: https://user:pass@someurl.com
  number_of_shards: 1                 # Optional. Default is 1 primary shard.
  number_of_replicas: 1               # Optional. Default is 1 replica.
  index_name: "jekyll"                # Optional. Default is "jekyll".
  default_type: "post"                # Optional. Default type is "post".
