# theme: jekyll-theme-hacker
remote_theme: andrewhwanpark/dark-poole
url: https://solutions.sem5.tk
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jemoji

relative_links:
  enabled: true
  collections: true

include:
  - README.md
