title: "Semester 5"

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jemoji

relative_links:
  enabled: true
  collections: true

include:
  - README.md

# https://github.com/abhinavs/moonwalk/blob/master/_config.yml
theme_config:
  appearance: "dark"
  back_home_text: "home.."
  date_format: "%Y-%m-%d"
  show_description: true
  # show_navbar: true
  show_footer: true
  show_projects: true
  show_misc_list: false
  show_blog: false
