# theme: jekyll-theme-hacker
remote_theme: andrewhwanpark/dark-poole
url: https://max-rocco.github.io/sem5
baseurl: /sem5

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jemoji

relative_links:
  enabled: true
  collections: true

include:
  - README.md
